test:
  image: registry.gitlab.com/silvam-filipe/forum-daf:latest
  cache:
    paths:
      - vendor/
  before_script:
    - composer install
  script:
    - vendor/bin/phpspec run -fdot
  tags:
    - build-machine